feat: what is PoP, what it can be
peppelinux/draft-demarco-oauth-status-attestations pull request #12
Opened 2024-02-13 17:22 UTC by peppelinux

this PR resolves the issue https://github.com/peppelinux/draft-demarco-oauth-status-attestations/issues/11

2024-02-14 12:36 UTC, fmarino-ipzs commented on draft-demarco-oauth-status-attestations.md
> +The essence of requiring control over the private key and its demonstration through a cryptographic operation (e.g., signing a challenge or a token) is to ensure that the entity in possession of the
```suggestion
The essence of requiring control over the private key and its demonstration through a cryptographic operation (e.g., signing a challenge or a token) is to ensure that the entity in possession of the credential can execute actions exclusively reserved for the legitimate owner. This dual-layered approach not only reinforces the security and integrity of the status attestation process but also affirms that the entity requesting a status attestation is the same entity to which the credential was issued. 
```

2024-02-14 12:40 UTC, fmarino-ipzs approved these changes
LGTM.
Btw, we are assuming here that the credential for which a Status Attestation is requested has a cryptographic holder-binding. Is this a right assumption? Should we generalize to cases where we have other holder binding mechanisms or even none?

2024-02-14 14:05 UTC, peppelinux commented on draft-demarco-oauth-status-attestations.md
> +The essence of requiring control over the private key and its demonstration through a cryptographic operation (e.g., signing a challenge or a token) is to ensure that the entity in possession of the
```suggestion
The essence of requiring control over the private key and its demonstration through a cryptographic operation (e.g., signing a challenge or a token) is to ensure that the entity in possession of the credential can execute actions exclusively reserved for the legitimate owner. The dual-layered approach of requiring both possession of the credential and control over the corresponding private key indeed reinforces the security and integrity of the status attestation process. It also ensures that the entity requesting a status attestation is indeed the same entity to which the credential was originally issued, affirming the authenticity and rightful ownership of the credential.
```

2024-02-23 21:39 UTC, peppelinux commented
@fmarino-ipzs This pull request addresses a limitation of the current specification. It currently only works with digital credentials that contain holder key binding.

2024-02-28 13:36 UTC, OR13 commented on draft-demarco-oauth-status-attestations.md
> +The essence of requiring control over the private key and its demonstration through a cryptographic operation (e.g., signing a challenge or a token) is to ensure that the entity in possession of the
```suggestion
The essence of requiring control over the private key and its demonstration through a cryptographic operation (e.g., signing a challenge or a token) is to ensure that the entity in possession of the credential can execute actions exclusively reserved for the legitimate subject. The dual-layered approach of requiring both possession of the credential and control over the corresponding private key indeed reinforces the security and integrity of the status attestation process. It also ensures that the entity requesting a status attestation is indeed the same entity to which the credential was originally issued, affirming the authenticity and rightful possession of the credential.
```

2024-02-28 13:37 UTC, OR13 requested changes
minor word changes, ideally we don't need to distinguish "owner" and "subject", and "ownership" and "possession".

2024-02-28 14:05 UTC, peppelinux commented on draft-demarco-oauth-status-attestations.md
> +The concept of Proof of Possession (PoP) of a Credential within the framework of the Status Attestation specification encompasses a broader perspective than merely possessing the digital bytes of the
```suggestion
The concept of Proof of Possession (PoP) of a Credential within the framework of the Status Attestation specification encompasses a broader perspective than merely possessing the digital bytes of the Credential. It involves demonstrating rightful control or ownership over the Credential, which can manifest in various forms depending on the technology employed and the nature of the digital Credential itself. For instance, a Credential could be presented visually (de-visu) with a personal portrait serving as a binding element.
```

2024-02-28 14:05 UTC, peppelinux commented on draft-demarco-oauth-status-attestations.md
> +While this specification does not prescribe any additional methods for the PoP of the credential, it aims to offer guidance for concrete implementations utilizing common PoP mechanisms. This includes
```suggestion
While this specification does not prescribe any additional methods for the proof of possession of the Credential, it aims to offer guidance for concrete implementations utilizing common proof of possession mechanisms. This includes, but is not limited to:
```

2024-02-28 14:05 UTC, peppelinux commented on draft-demarco-oauth-status-attestations.md
> +2. Controlling a private key that corresponds to a public key associated with the credential, often indicated within the credential's cnf (confirmation) claim or through a similar mechanism.
```suggestion
2. Controlling a private key that corresponds to a public key associated with the Credential, often indicated within the Credential's cnf (confirmation) claim or through a similar mechanism.
```

2024-02-28 14:05 UTC, peppelinux commented on draft-demarco-oauth-status-attestations.md
> +The essence of requiring control over the private key and its demonstration through a cryptographic operation (e.g., signing a challenge or a token) is to ensure that the entity in possession of the
```suggestion
The essence of requiring control over the private key and its demonstration through a cryptographic operation (e.g., signing a challenge or a token) is to ensure that the entity in possession of the Credential can execute actions exclusively reserved for the legitimate subject. The dual-layered approach of requiring both possession of the Credential and control over the corresponding private key indeed reinforces the security and integrity of the status attestation process. It also ensures that the entity requesting a Status Attestation is indeed the same entity to which the Credential was originally issued, affirming the authenticity and rightful possession of the Credential.
```

2024-02-28 14:07 UTC, OR13 approved these changes

2024-02-28 14:08 UTC, merged